import Head from "next/head";
import styles from "../styles/Home.module.css";
import Button from "@mui/material/Button";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>First App</h1>
        <Button variant="contained">Contained</Button>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
